# Generated by Django 3.0.4 on 2020-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0004_auto_20200503_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('Intervals', 'Intervals'), ('Year', 'Year')], max_length=15, null=True),
        ),
    ]
