# Generated by Django 3.0.4 on 2020-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0005_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
