# Generated by Django 3.0.4 on 2020-05-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0006_order_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('Intervals', 'Intervals'), ('Year', 'Year')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='model_type',
            field=models.CharField(choices=[('PCA & Logit', 'PCA & Logit')], default='PCA & Logit', max_length=128),
        ),
        migrations.CreateModel(
            name='OrderResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('y_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('graph_url', models.URLField(blank=True, null=True)),
                ('graph_image', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation.Order')),
            ],
        ),
    ]
