# Generated by Django 3.0.4 on 2020-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0007_auto_20200505_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attribute_name',
            field=models.CharField(blank=True, choices=[('Патенты', 'X1'), ('Все активы', 'X4'), ('Гудвилл', 'X5'), ('R&D', 'X6'), ('Материальные активы', 'X7'), ('Кол-во поглощений', 'X11'), ('Доля сотрудников НИОКР', 'X13'), ('ЗП', 'X14'), ('Амортизация', 'X15'), ('Возраст', 'X16')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('Convolution', 'Convolution'), ('Intervals', 'Intervals'), ('Year', 'Year')], default='Convolution', max_length=64),
        ),
    ]
