# Generated by Django 3.0.4 on 2020-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0008_auto_20200506_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attribute_name',
            field=models.CharField(blank=True, choices=[('Патенты', 'Патенты'), ('Все активы', 'Все активы'), ('Гудвилл', 'Гудвилл'), ('R&D', 'R&D'), ('Материальные активы', 'Материальные активы'), ('Кол-во поглощений', 'Кол-во поглощений'), ('Доля сотрудников НИОКР', 'Доля сотрудников НИОКР'), ('ЗП', 'ЗП'), ('Амортизация', 'Амортизация'), ('Возраст', 'Возраст')], max_length=32, null=True),
        ),
    ]
