# Generated by Django 3.0.4 on 2020-05-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0009_auto_20200506_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresult',
            name='p_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
