# Generated by Django 3.0.4 on 2020-05-28 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0010_orderresult_p_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attribute_name',
            field=models.CharField(blank=True, choices=[('Патенты', 'Патенты'), ('Все активы', 'Все активы'), ('Гудвилл', 'Гудвилл'), ('R&D', 'R&D'), ('Материальные активы', 'Материальные активы'), ('Кол-во поглощений', 'Кол-во поглощений'), ('Доля сотрудников НИОКР', 'Доля сотрудников НИОКР'), ('ЗП', 'ЗП'), ('Амортизация', 'Амортизация'), ('Возраст', 'Возраст')], max_length=32, null=True, verbose_name='Показатель для тренда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='build_graphics',
            field=models.BooleanField(default=False, verbose_name='Построить график тренда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Данные о компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('Convolution', 'Convolution'), ('Intervals', 'Intervals'), ('Year', 'Year')], default='Convolution', max_length=64, verbose_name='Метод расчетв'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model_type',
            field=models.CharField(choices=[('PCA & Logit', 'PCA & Logit')], default='PCA & Logit', max_length=128, verbose_name='Тип модели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала интервала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год конца интервала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
