# Generated by Django 3.0.4 on 2020-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0011_auto_20200528_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('Convolution', 'Convolution'), ('Intervals', 'Intervals'), ('Year', 'Year')], default='Convolution', max_length=64, verbose_name='Метод расчета'),
        ),
    ]
