# Generated by Django 3.0.4 on 2020-05-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0012_auto_20200528_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderresult',
            name='graph_url',
        ),
    ]
